<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>ExpenseIQ Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:13px;
            color:#333;
            margin:35px;
        }

        .header{

            border-bottom:4px solid #F3C400;
            padding-bottom:15px;
            margin-bottom:25px;

        }

        .title{

            font-size:30px;
            font-weight:bold;
            color:#B88900;

        }

        .subtitle{

            font-size:18px;
            margin-top:4px;
            color:#666;

        }

        .generated{

            font-size:11px;
            color:#777;
            margin-top:10px;

        }

        .summary{

            width:100%;
            margin-top:20px;
            margin-bottom:25px;

        }

        .summary td{

            border:1px solid #DDD;
            padding:12px;

        }

        .summary .label{

            width:45%;
            background:#FFF8D8;
            font-weight:bold;

        }

        .summary .value{

            text-align:right;

        }

        h2{

            color:#B88900;
            margin-top:25px;
            margin-bottom:10px;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        th{

            background:#F3C400;
            color:#333;
            padding:10px;
            border:1px solid #DDD;

        }

        td{

            border:1px solid #DDD;
            padding:9px;

        }

        tbody tr:nth-child(even){

            background:#FAFAFA;

        }

        .amount{

            text-align:right;

        }

        .footer{

            margin-top:35px;
            text-align:center;
            font-size:11px;
            color:#777;

        }

    </style>

</head>

<body>

<div class="header">

    <div class="title">
        ExpenseIQ
    </div>

    <div class="subtitle">
        Monthly Financial Report
    </div>

    <div class="generated">
        Generated on {{ now()->format('F d, Y h:i A') }}
    </div>

</div>

<p>

    <strong>Report Period:</strong>

    {{ \Carbon\Carbon::parse($from)->format('F d, Y') }}

    -

    {{ \Carbon\Carbon::parse($to)->format('F d, Y') }}

</p>

<table class="summary">

    <tr>

        <td class="label">

            Total Budget

        </td>

        <td class="value">

            ₱{{ number_format($report['totalBudget'],2) }}

        </td>

    </tr>

    <tr>

        <td class="label">

            Total Expenses

        </td>

        <td class="value">

            ₱{{ number_format($report['totalExpenses'],2) }}

        </td>

    </tr>

    <tr>

        <td class="label">

            Remaining Budget

        </td>

        <td class="value">

            ₱{{ number_format($report['remainingBudget'],2) }}

        </td>

    </tr>

</table>

<h2>

Expense Details

</h2>

<table>

    <thead>

        <tr>

            <th width="22%">Category</th>

            <th width="38%">Description</th>

            <th width="18%">Amount</th>

            <th width="22%">Date</th>

        </tr>

    </thead>

    <tbody>

    @forelse($report['expenses'] as $expense)

        <tr>

            <td>

                {{ $expense->category->category_name }}

            </td>

            <td>

                {{ $expense->description }}

            </td>

            <td class="amount">

                ₱{{ number_format($expense->amount,2) }}

            </td>

            <td>

                {{ \Carbon\Carbon::parse($expense->expense_date)->format('M d, Y') }}

            </td>

        </tr>

    @empty

        <tr>

            <td colspan="4" style="text-align:center;">

                No expense records found.

            </td>

        </tr>

    @endforelse

    </tbody>

</table>

<div class="footer">

    Generated by ExpenseIQ

</div>

</body>

</html>